
# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  l5-tradermanager-mysql-data:
    driver: local

  # Redis Data
  l5-tradermanager-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: l5-tradermanager-mysql
    volumes:
      - l5-tradermanager-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tradermanager
      - MYSQL_DATABASE=tradermanager
      - MYSQL_USER=tradermanager
      - MYSQL_PASSWORD=tradermanager

  # Redis
  cache:
    image: redis:4.0
    container_name: l5-tradermanager-redis
    command: --appendonly yes
    volumes:
      - l5-tradermanager-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: l5-tradermanager-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: l5-tradermanager-queue
    command: composer update && php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache